---
  ##########################################################################
  #                                                                        #
  #                                Settings                                #
  #                                                                        #
  ##########################################################################

  anchors:
    # Empty placeholder for correct positioning
    ⚓₁: &anchor-placeholder-card
      # Button card. See: https://github.com/custom-cards/button-card
      - type: custom:button-card
        color_type: blank-card
    ⚓₂: &custom-scenes-style
      .: |
        ha-card {
          transition: background-color 0.2s ease 0.5s;
          background-color: var(--accent-color, var(--accent-color, white) );
        }
        .card-header {
          color: var(--text-primary-color);
          font-size: 16px;
          font-weight: 500;
          font-variant: small-caps;
          padding-top: 16px;
          line-height: 16px;
        }
    ⚓₃: &custom-header-style
      .: |
        .card-header {
          font-size: 16px;
          font-weight: 500;
          font-variant: small-caps;
          padding-top: 16px;
          line-height: 16px;
        }
    ⚓₄: &custom-scenes-style-mod-card
      .: |
        #root {
          background-color: var(--accent-color, var(--accent-color, white) );
        }
    ⚓₅: &default_slider_options
      tap_action:
        action: toggle
      double_tap_action:
        action: more-info

  ##########################################################################
  #                                                                        #
  #                                Lovelace                                #
  #                                                                        #
  ##########################################################################
  
  title: Instellingen
  path: settings
  icon: mdi:cogs
  badges: []
  visible:
    - user: 66b3f3ae00d44e8287a631b636e599f5
  cards:
    # Stack in Card. See: https://github.com/custom-cards/stack-in-card
    - type: vertical-stack
      cards:

        #############################
        #                           #
        #          Scenes           #
        #                           #
        #############################
        # Stack in Card. See: https://github.com/custom-cards/stack-in-card
        - type: custom:stack-in-card
          title: scenes
          style:
            << : *custom-scenes-style
          mode: 'vertical'
          cards:

            # Horizontal stack card. See: https://www.home-assistant.io/lovelace/horizontal-stack
            - type: horizontal-stack
              cards:

                - << : *anchor-placeholder-card
