---
# See: https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  time_zone: Europe/Amsterdam

  unit_system: metric
  internal_url: !secret internal_url
  external_url: !secret external_url

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: !secret trusted_networks

  auth_mfa_modules:
    - type: totp

  # Load all packages from the 'integrations' folder
  packages: !include_dir_named integrations

  # Customize individual entities
  customize: !include_dir_merge_named customize/entities

  # Custimize all entities in a domain
  customize_domain: !include_dir_merge_named customize/domains

  # Custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named customize/globs
