---
  ##################################################################
  # <DEFAULTS>                                                     #
  # Defaults from default integration meta-component               #
  # See https://www.home-assistant.io/integrations/default_config/ #
  ##################################################################

  updater:
    reporting: true
    include_used_components: true

  # Sun integration. See: https://www.home-assistant.io/integrations/sun/
  sun:
    
  # Home Assistant Cloud. See: https://www.home-assistant.io/integrations/cloud/
  cloud:
  
  # See: https://www.home-assistant.io/integrations/config/
  config:

  # See: https://www.home-assistant.io/integrations/frontend/
  frontend:

  # See: https://www.home-assistant.io/integrations/image/
  image:
    
  # See: https://www.home-assistant.io/integrations/map/
  map:

  # Media Source integration. See: https://www.home-assistant.io/integrations/media_source/
  media_source:
    
  # See: https://www.home-assistant.io/integrations/mobile_app/
  mobile_app:

  # See: https://www.home-assistant.io/integrations/ssdp/
  ssdp:
    
  # See: https://www.home-assistant.io/integrations/system_health/
  system_health:
    
  # See: https://www.home-assistant.io/integrations/tag/
  # tag:
    
  # See: https://www.home-assistant.io/integrations/zeroconf/
  zeroconf:

  # See: https://www.home-assistant.io/integrations/automation/
  automation: !include automations.yaml

  # See: https://www.home-assistant.io/integrations/history/
  history: !include history.yaml
  
  # See: https://www.home-assistant.io/integrations/logbook/
  logbook: !include logbook.yaml
  
  # See: https://www.home-assistant.io/integrations/person/
  person: !include person.yaml

  # See: https://www.home-assistant.io/integrations/scene/
  scene: !include scene.yaml

  # See: https://www.home-assistant.io/integrations/script/
  script: !include scripts.yaml

  # See: https://www.home-assistant.io/integrations/zone/
  zone: !include zone.yaml

  input_boolean: !include_dir_merge_named inputs\input_boolean      # See: https://www.home-assistant.io/integrations/input_boolean
  input_datetime: !include_dir_merge_named inputs\input_datetime    # See: https://www.home-assistant.io/integrations/input_datetime
  input_number: !include_dir_merge_named inputs\input_number        # See: https://www.home-assistant.io/integrations/input_number
  input_select: !include_dir_merge_named inputs\input_select        # See: https://www.home-assistant.io/integrations/input_select
  input_text: !include_dir_merge_named inputs\input_text            # See: https://www.home-assistant.io/integrations/input_text

  ##################################################################
  # </DEFAULTS>                                                    #
  ##################################################################

  # Text to speech. See: https://www.home-assistant.io/integrations/tts/
  tts:
    # - platform: amazon_polly        # See: https://www.home-assistant.io/integrations/amazon_polly/
    #   aws_access_key_id: 'AKIATEELDYSLWSJE5FRV'
    #   aws_secret_access_key: '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'
    #   region_name: 'eu-central-1'
    #   text_type: text
    #   voice: Joanna
    #   cache: True
    - platform: google_translate
      base_url: !secret tts_base_url
      service_name: google_translate_say

    # See: https://www.home-assistant.io/integrations/group/
  group: !include groups.yaml

  # See: https://www.home-assistant.io/integrations/lovelace/
  lovelace: !include lovelace.yaml

  # See: https://www.home-assistant.io/integrations/logger/
  logger: !include logger.yaml

  # See: https://www.home-assistant.io/integrations/recorder/
  recorder: !include recorder.yaml

  # See: https://www.home-assistant.io/integrations/http/
  http:
    # ssl_certificate: /ssl/fullchain.pem
    # ssl_key: /ssl/privkey.pem
    ip_ban_enabled: true
    login_attempts_threshold: 5
    
  # See: https://www.home-assistant.io/integrations/weather/
  weather:
    - platform: buienradar
      name: home

  # See: https://www.home-assistant.io/integrations/sensor/
  sensor:
    - platform: buienradar
      name: buienradar
      timeframe: 60
      monitored_conditions:
        - stationname
        - temperature
        - feeltemperature
        - windspeed
        - winddirection
        - visibility
        - humidity
        - pressure
        - symbol
        - conditiondetailed
        - conditiondetailed_1d

  # See: https://www.home-assistant.io/integrations/homeassistant/
  homeassistant:
    name: Home

    # Location required to calculate the time the sun rises and sets
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    elevation: !secret elevation_home
    time_zone: Europe/Amsterdam
    
    unit_system: metric
    internal_url: !secret internal_url
    external_url: !secret external_url

    auth_providers:
      - type: homeassistant
      - type: trusted_networks
        trusted_networks: !secret trusted_networks

    customize: !include customize.yaml
