---
  # Configure a default setup of Home Assistant (frontend, api, etc)
  # See https://www.home-assistant.io/integrations/default_config/
  # default_config:

  updater:
    reporting: true
    include_used_components: true

  # Text to speech. See https://www.home-assistant.io/integrations/tts/
  tts:
    - platform: google_translate
    
    # See: https://www.home-assistant.io/integrations/person/
  person: !include person.yaml

    # See: https://www.home-assistant.io/integrations/group/
  group: !include groups.yaml

  # See: https://www.home-assistant.io/integrations/automation/
  automation: !include automations.yaml

  # See: https://www.home-assistant.io/integrations/script/
  script: !include scripts.yaml

  # See: https://www.home-assistant.io/integrations/scene/
  scene: !include scenes.yaml
  
  # See: https://www.home-assistant.io/integrations/lovelace/
  lovelace: !include lovelace.yaml

  # See: https://www.home-assistant.io/integrations/logger/
  logger: !include logger.yaml

  # See: https://www.home-assistant.io/integrations/recorder/
  recorder: !include recorder.yaml

  # See: https://www.home-assistant.io/integrations/history/
  history: !include history.yaml
  
  # https://www.home-assistant.io/integrations/http/
  http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
    ip_ban_enabled: true
    login_attempts_threshold: 5
    
  # https://www.home-assistant.io/integrations/homeassistant/
  homeassistant:
    name: Home

    # Location required to calculate the time the sun rises and sets
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    elevation: !secret elevation_home
    time_zone: Europe/Amsterdam
    
    unit_system: metric
    internal_url: !secret internal_url

    auth_providers:
      - type: homeassistant
      - type: trusted_networks
        trusted_networks:
          - 10.72.0.0/16

    customize: !include customize.yaml

  # https://www.home-assistant.io/integrations/zone/
  zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 100
    icon: mdi:home

  # See: https://www.home-assistant.io/integrations/weather/
  weather:
    - platform: buienradar
      name: home

  # https://www.home-assistant.io/integrations/sensor/
  sensor:
    - platform: buienradar
      name: buienradar
      timeframe: 60
      monitored_conditions:
        - stationname
        - temperature
        - feeltemperature
        - windspeed
        - winddirection
        - visibility
        - humidity
        - pressure
        - symbol
        - conditiondetailed
        - conditiondetailed_1d
