---
title: Scheidiuslaan 72
views:
  - !include lovelace/view-home.yaml
  - !include lovelace/view-ground-floor.yaml
  - !include lovelace/view-first-floor.yaml
  - !include lovelace/view-second-floor.yaml
  - !include lovelace/view-music.yaml
  - !include lovelace/view-outside.yaml
